### ISSUE TITLE
Магические числа

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#1]
Все константы выносятся в начало модуля
Здесь:
https://github.com/Vadimfre/keksagram-Semashko/blob/963e04497931c0101806948c5e5adcec2203d098/kekstagram-clear/main.js#L63
Здесь:
https://github.com/Vadimfre/keksagram-Semashko/blob/963e04497931c0101806948c5e5adcec2203d098/kekstagram-clear/main.js#L114-L115

**Comment by Vadimfre** [comment]
`const WIDTHCOMMENT = 35;
const HEIGHTCOMMENT = 35;
  commentPhoto.width = WIDTHCOMMENT;
  commentPhoto.height = HEIGHTCOMMENT;`
   вот тут я ,,Снял чары и проявил,, магические числа, теперь это константы, где ширина и длина указаны
   
`      avatar: `img/avatar-${getRandomInt(1, COMMAVATARMAX)}.svg`,
const COMMAVATARMAX = 6;` так вот тут сделал тоже самое
