### ISSUE TITLE
Работа с шаблоном

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#10]
Шаблон - это особая штука...
https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L75
https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L77

По итогу здесь ты получаешь не pictureElement, а фрагмент, что некорректно. Правильнее будет сразу в шаблон вытащить разметку и уже разметку потом клонировать. Сделать это банально просто:
`const pictureTemplate = document.querySelector("#picture").content.querySelector(".picture");`

**Comment by Vadimfre** [comment]
Да, теперь я понял,  https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L75-L77
