### ISSUE TITLE
Дублирование кода 

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#11]
Наблюдается нарушение принципа DRY. 
https://github.com/Vadimfre/keksagram-Semashko/blob/552c85e71a9c1ee7baebc59edd6a390fdcac0c60/main.js#L166-L176
Все повторяющиеся участки кода нужно выносить в функцию...
```
imageEditForm.classList.add("hidden");
uploadFile.value = "";
```

**Comment by Vadimfre** [comment]
ну вот как я сделал  https://github.com/Vadimfre/keksagram-Semashko/blob/ab1d91f18403993c6e182cf626586d88c14708a2/main.js#L174-L176
