### ISSUE TITLE
Обработчики событий

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#12]
В данном случае имеет смысл создать именованный обработчик
https://github.com/Vadimfre/keksagram-Semashko/blob/552c85e71a9c1ee7baebc59edd6a390fdcac0c60/main.js#L88-L90
Не забудь, что у функций-обработчиков имя функции строится по особому принципу (см. критерии)

**Comment by Morfey216** [comment]
№2
В критериях есть пункт о том, что обработчики должны добавляться и удаляться своевременно. Это означает, что если модальное окно закрыто, то нам не нужны обработчики его закрытия. Обработчики закрытия окна должны добавляться ровно тогда, когда окно открывается. При закрытии окна обработчики закрытия нужно удалить.
https://github.com/Vadimfre/keksagram-Semashko/blob/552c85e71a9c1ee7baebc59edd6a390fdcac0c60/main.js#L166-L176

**Comment by Vadimfre** [comment]
сразу с пункта 2 вот тут сделал  вот так вот https://github.com/Vadimfre/keksagram-Semashko/blob/ab1d91f18403993c6e182cf626586d88c14708a2/main.js#L174-L180 эта функция просто скрывает фотку, ну и сразу удаляет обработчики, тут вылезла другая проблема, обработчики должны быть именованные,  https://github.com/Vadimfre/keksagram-Semashko/blob/ab1d91f18403993c6e182cf626586d88c14708a2/main.js#L182-L190 но решилось это быстро, ну и еще одна деталька обработчики начал добавлять только как произошло событие change https://github.com/Vadimfre/keksagram-Semashko/blob/ab1d91f18403993c6e182cf626586d88c14708a2/main.js#L167-L172

**Comment by Vadimfre** [comment]
а вот с первым пунктиком была проблемка, я то ее решил, но думаю, что решение плохое https://github.com/Vadimfre/keksagram-Semashko/blob/ab1d91f18403993c6e182cf626586d88c14708a2/main.js#L94-L95 пришлось добавлять вот так вот, ведь в этих обработчиках мне нужна photodata для открытия, решил создать функцию https://github.com/Vadimfre/keksagram-Semashko/blob/ab1d91f18403993c6e182cf626586d88c14708a2/main.js#L74-L78 которая возвращает функцию и засунул ее в переменную в цикле а дальше создал обработчик

**Comment by Morfey216** [comment]
> а вот с первым пунктиком была проблемка, я то ее решил, но думаю, что решение плохое

Честно - я так и не понял, для чего такие сложности...
Решение нужно менять!

**Comment by Vadimfre** [comment]
поменял, каждой картинке присвоил data-index, только пришлось из-за этого и поменять цикл,  можно было бы не менять, но пришлось бы создавать новую переменную, потом сделать так, чтобы при каждом проходе цикла к ней добавлялась 1 и это присваивалось и  data-index , но решил сделать вот так https://github.com/Vadimfre/keksagram-Semashko/blob/130786ec01926386a554b06399dee4feddbacfee/main.js#L86-L96 https://github.com/Vadimfre/keksagram-Semashko/blob/130786ec01926386a554b06399dee4feddbacfee/main.js#L75-L80

**Comment by Morfey216** [comment]
Уже близко... Цикл надо доработать...
https://github.com/Vadimfre/keksagram-Semashko/blob/130786ec01926386a554b06399dee4feddbacfee/main.js#L86
Основной проблемой является итерация до значения TOTAL_NUMBER_OF_PHOTOS. Это сработает только в том случае, если количество картинок равно TOTAL_NUMBER_OF_PHOTOS, но так будет не всегда: например - фильтр изображений по количеству лайков даст не 25картинок, а, например, 16

Посмотри в сторону метода массива forEach
https://learn.javascript.ru/array-methods
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/27592f68ff0968598d481729f51fa5e26f91a03c/main.js#L86-L97 ну вот, прикольная штука, изучил ее

**Comment by Morfey216** [comment]
OK
На данном этапе пока остановимся
