### ISSUE TITLE
Неправильная оценка количества хэштегов

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#14]
Смотри скрин:
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/f86b05c2-6a8a-4bb1-b558-867357841721)

**Comment by Vadimfre** [comment]
Это то вообще ужас какой-то был, пришлось переделывать, я что-то вообще об этом не подумал, теперь схема такая, что если у какой-нибудь строчки( хештега) нету решетки, оно сразу выдает ошибку и не идет дальше пока человек не исправил,  https://github.com/Vadimfre/keksagram-Semashko/blob/6ce3697eeb6746e86b14845e402a33fa3affa18a/main.js#L253-L268 
https://github.com/Vadimfre/keksagram-Semashko/blob/6ce3697eeb6746e86b14845e402a33fa3affa18a/main.js#L243-L251

**Comment by Morfey216** [comment]
Вот еще для примера

![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/0253c8fc-b807-436f-ae64-20acc6c73132)
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/aa5aa476-dbcf-442f-8e07-58784d0ec0fc)

**Comment by Vadimfre** [comment]
такс, 1 скрин я сделал это нужно было описать ошибку, что внутри хештега нельзя писать #, это исправлено, а второй скрин наверное пробел в конце всего, тоже это убрал вот так  https://github.com/Vadimfre/keksagram-Semashko/blob/660afce0cb926f298bbb5461ad9cd889acaaf1a2/main.js#L286, решил просто это пробел не считать, ведь я любитель в каждом сообщении перед отправкой в конце поставить пробел, думаю я такой не один  https://github.com/Vadimfre/keksagram-Semashko/blob/660afce0cb926f298bbb5461ad9cd889acaaf1a2/main.js#L22
