### ISSUE TITLE
Алгоритм обновления сообщения об ошибке

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#15]
Думаю, было бы правильно, если бы сообщение обновлялось при внесении правок, дабы не вводить пользователя в заблуждение... А то получим вот такую проблему:
https://gyazo.com/db7c18bd9e3af1c0baa9dda8b7cd0e78

**Comment by Vadimfre** [comment]
ну это да только вот как лучше, чтобы сообщение полностью удалялось или же прогонять после изменения опять на ошибки, я сделал чтобы удалилось  https://github.com/Vadimfre/keksagram-Semashko/blob/252a3911963fd2b065bb99414eec3e8019e19d8e/main.js#L305-L307

**Comment by Morfey216** [comment]
1. Сообщение должно обновляться, а не очищаться
2. Ты добавил анонимный обработчик, снять который при закрытии окна или отправке формы будет невозможно

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/73075e283ab2f4e9a543180b942678706856c973/main.js#L321-L325 сделал вот так ну и соответственно удалил его https://github.com/Vadimfre/keksagram-Semashko/blob/660afce0cb926f298bbb5461ad9cd889acaaf1a2/main.js#L241

**Comment by Morfey216** [comment]
Даже упоминать не хочется, что исправляя одну ошибку ты влепил другую...
https://github.com/Vadimfre/keksagram-Semashko/blob/660afce0cb926f298bbb5461ad9cd889acaaf1a2/main.js#L326

Уже было ведь
https://github.com/Vadimfre/keksagram-Semashko/issues/20#issue-2268404160

**Comment by Vadimfre** [comment]
Постараюсь больше такого не допускать  https://github.com/Vadimfre/keksagram-Semashko/blob/2506c1ec71a12ae130592d54257123d2827bfc1c/main.js#L327-L331
