### ISSUE TITLE
Текст ошибки вводит в заблуждение

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#17]
См. скрин
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/5c4b86d3-f1d2-48f2-8881-ed6906f3ff05)

О какой ошибке здесь говорится?

И в чем я, как пользователь, неправ? Один хэштег, начинается с решетки - всё ведь соответствует формату

**Comment by Vadimfre** [comment]
Что-то я реально затупил https://github.com/Vadimfre/keksagram-Semashko/blob/252a3911963fd2b065bb99414eec3e8019e19d8e/main.js#L17 теперь будет вот такой текст, более понятно

**Comment by Morfey216** [comment]
Не уверен, что твои правки помогли

![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/5fe6e2fa-978f-4eea-b491-448ec6513c6f)

**Comment by Vadimfre** [comment]
не знаю как вы добились такой ошибки блин, тут есть ошибка, 'Один и тот же хэш-тег не может быть использован дважды', но чтобы вот такая...

**Comment by Morfey216** [comment]
Может так поможет?..

![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/5abe9106-fb72-48e9-a69a-2e25a8f78fd4)

**Comment by Vadimfre** [comment]
а тут проблема с 2 пробелами, я понял, вот исправил https://github.com/Vadimfre/keksagram-Semashko/blob/2506c1ec71a12ae130592d54257123d2827bfc1c/main.js#L291
