### ISSUE TITLE
Именование функций

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#2]
Название функции или метода должно содержать глагол и соответствовать действию, которое выполняет функция или метод.

Как пример
https://github.com/Vadimfre/keksagram-Semashko/blob/963e04497931c0101806948c5e5adcec2203d098/kekstagram-clear/main.js#L89

Или здесь
https://github.com/Vadimfre/keksagram-Semashko/blob/963e04497931c0101806948c5e5adcec2203d098/kekstagram-clear/main.js#L41

В первом случае нет глагола, а во втором - не соответствует тому, что делает функция. 
Функция createPhoto на самом деле генерирует данные для картинок, причем для всех, а не для одной. Тут больше подошло бы, например, createPhotosData или что-то в этом роде

**Comment by Vadimfre** [comment]
[https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js#L45] вот  тут изменил, как вы мне и подсказали, перечитал как правильно подписывается
[https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js#L91C4-L91C16] вот тут поменял название тоже была раньше bigPicture

**Comment by Vadimfre** [comment]
[https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js#L91C4-L91C16](url) вот это bigPicture

[https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js#L45](url) вот это уже createPhoto

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js#L45 вот это 1 функция  createPhoto переименовал

https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js#L91 вот это функция bigPicture

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plain=1#L45 вот это функция createPhoto уже переименованная

**Comment by Vadimfre** [comment]
а вот это уже https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plain=1#L91 функция bigPicture которая  показывает большую фотографию

**Comment by Morfey216** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L60

Здесь не понятно, что делает функция

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L62 я исправил и поменял название

**Comment by Morfey216** [comment]
> https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L62
> 
> я исправил и поменял название

А если это не random коммент, а вполне настоящий, что тогда?

**Comment by Morfey216** [comment]
> https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L62
> 
> я исправил и поменял название

А если это не random коммент, а вполне настоящий, что тогда?
И насколько я помню, тут не один коммент создается, а сразу много )

**Comment by Vadimfre** [comment]
Ох этот нейминг https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L59

**Comment by Morfey216** [comment]
> Ох этот нейминг
> 
> https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L59

Нейминг работает в коде намного круче, чем ты думаешь ))
Написал const comment = чегототам и другой разработчик только лишь по имени понимает, что это комментарий и он один. А как только поменял на comments - речь сразу идет о массиве. Мозг именно так это все воспринимает и очень странно, когда по коду ждешь одно, а функция отправляет другое

На нейминг при разработке, согласно статистике, тратится до 30% рабочего времени!
