### ISSUE TITLE
Логика работы функций

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#3]
Если ты внимательно посмотришь на то, что показывает сайт, то увидишь, что комментариев везде ровно по одному
https://gyazo.com/729288f3c6f2b86b9ae3c567251df82d

Вся проблема в том, как ты создаешь и добавляешь комментарии
https://github.com/Vadimfre/keksagram-Semashko/blob/963e04497931c0101806948c5e5adcec2203d098/kekstagram-clear/main.js#L49

Ну и по традиции - нейминг... Если из функции ты возвращаешь массив, то и название у него должно быть во множественном числе

Далее - функция должна заниматься только своим делом, не нужно на нее навешивать чужие задачи и смешивать функционалы... Привожу пример

![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/a6d9f851-3a2d-4430-ae6b-3edfa949fbe0)
Есть две разные функции, которые делают разные вещи - для чего ты связал их командой вызова? Если хочешь вначале получить данные, а потом их отрисовать на странице, то так и напиши:
createPhoto();
uploadPhoto();

тем более, что место для этого ты уже обозначил

**Comment by Vadimfre** [comment]
с комментариями у меня все ок и везде по одному.
![Снимок экрана 2024-04-11 103729](https://github.com/Vadimfre/keksagram-Semashko/assets/147087151/d9477c0e-8a5b-4540-a000-7bea08a679bb)
вот теперь каждая не функция вызывает функцию

**Comment by Vadimfre** [comment]
хмм, у меня везде по одному комментрию https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js?plain=1#L41-L87 вот уже я сам вызываю функцию вызываю вне другой

**Comment by Morfey216** [comment]
> хмм, у меня везде по одному комментрию https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js?plain=1#L41-L87 вот уже я сам вызываю функцию вызываю вне другой

Ну, я же написал выше: "Вся проблема в том, как ты создаешь и добавляешь комментарии". Думаю, тебе нужно внимательнее посмотреть на код функции, которая сейчас у тебя _commentsSpawn_

Далее я написал "Ну и по традиции - нейминг... Если из функции ты возвращаешь массив, то и название у него должно быть во множественном числе" - видимо ты на это не обратил внимание.

Давай разбираться...
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L53
Здесь ты создаешь переменную **comment**, то есть ты ожидаешь получить ОДИН комментарий, ведь по неймингу comment - это НЕ массив. Пока что так и есть - из функции **commentsSpawn** ты возвращаешь ОДИН комментарий...
Но ведь ты не этого хотел, верно? Иначе зачем тебе цикл внутри функции...

Идем далее... Разбираемся, где ты накосячил в функции
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L60-L71
Командой выхода из функции является
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L69
Где написана эта команда? ВНУТРИ цикла...

Но даже ее вынос за пределы цикла не исправит ситуацию... Что такое commentData? Наверное - один комментарий. И что с ним происходит после генерации данных? С командой return он благополучно вылетает из функции... Занавес ))

Как должно быть...
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/308ee993-bde1-41f3-9f8f-5053eb543c3f)

**Comment by Vadimfre** [comment]
Это конечно да, ужас, перечитал код, все переделал, пришлось добавить еще один цикл for, ведь я возвращал уже массив, который нужно было бы ''распаковать'' , что я и сделал в функции но думаю это не лучший способ ведь функция становится не очень. https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L45-L75  еще на уме был другой подход создать новую функцию и там, но тогда пришлось бы вызывать из одной функции другую вот так:`function addCommentsToPhoto(photoData, comments) {
  for (let j = 0; j < comments.length; j++) {
    photoData.comments.push(comments[j]);
  }
  return photoData;
}

function createPhotosData() {
  for (let i = 1; i <= PHOTO_QUANTITY; i++) {
    const photoData = {
      url: `photos/${i}.jpg`,
      likes: getRandomInt(LIKE_MIN, LIKE_MAX),
      comments: [],
      description: getRandomArrayElement(DESCRIPTIONS),
    };
    const comments = createRandomComment();
    addCommentsToPhoto(photoData, comments);
    photosData.push(photoData);
` не знаю как будет лучше сделать,

**Comment by Vadimfre** [comment]
Это конечно да, ужас, перечитал код, все переделал, пришлось добавить еще один цикл for, ведь я возвращал уже массив, который нужно было бы ''распаковать'' , что я и сделал в функции но думаю это не лучший способ ведь функция становится не очень. https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L45-L75  еще на уме был другой подход создать новую функцию и там, но тогда пришлось бы вызывать из одной функции другую вот так:
![Снимок экрана 2024-04-12 124628](https://github.com/Vadimfre/keksagram-Semashko/assets/147087151/49b56160-5e96-40e8-b6e4-79e5edf5e14d)


 не знаю как будет лучше сделать, нейминг поправил

**Comment by Morfey216** [comment]
Вот чудо-человек )))
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js#L53-L57
Вся вот эта твоя кухня решается одной строчной кода

      photoData.comments =  createComments();

**Comment by Vadimfre** [comment]
АХАХХААХ, это просто ГЕНИАЛЬНО, я был в шоке!
https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L53
