### ISSUE TITLE
let vs const

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#4]
Уже поднимали эту тему...
https://github.com/Vadimfre/keksagram-Semashko/blob/963e04497931c0101806948c5e5adcec2203d098/kekstagram-clear/main.js#L43

**Comment by Vadimfre** [comment]
я понял, логично, переделал https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js?plain=1#L47 это я перензвал переменную ведь там переменная отвечает за данные фотографии и вот еще https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js?plain=1#L64 вот тут под комменты я тоже создал константу

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plain=1#L47
я понял, логично, переделал это под комментарий
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plain=#L47  это уже фото я чуть переназвал переменную мне кажется так лучше

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plane=1#L47
это уже фото я чуть переназвал переменную мне кажется так лучше
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.j?plane=1#L64 вот еще под комменты, думаю так лучше будет

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plain=1#L64 вот это под комментарии переделал

https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plain=1#L47 вот это где вы и сказали, чуть переназвал переменную, думаю так будет лучше

**Comment by Morfey216** [comment]
А мне всегда нужно будет указывать для тебя все встречающиеся варианты? ))
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L32
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L53
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L61
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L74
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L88-L89
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L105
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L116
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L125-L130
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L139-L140


Для упрощения есть правило, работает в 98% случаев:
1. Всегда вначале объявляем через const
2. Если выдает ошибку - меняем на let

**Comment by Vadimfre** [comment]
Оуу, такого тут я не ожидал, разобрался и все поправил 
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L32
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L53
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L63-L64
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L78
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L92-L93
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L109
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L120
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L129
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L133-L134
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L143-L144

**Comment by Morfey216** [comment]
Уже гораздо лучше, молодец!
Но я тебя удивлю - здесь тоже const:
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js#L79
https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js#L128

Нет, можно, конечно, и let, но всё же в данном случае const...
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/a8081191-7059-4711-881f-e2583e8bbd30)
Вот ссылка: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/for...of

**Comment by Vadimfre** [comment]
теперь буду знать наверняка!  https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L76 https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L125 
Разобрался как это работает! столько косяков просто ужас
