### ISSUE TITLE
Оптимизация поиска по DOM-дереву

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#5]
Поиск элементов по селекторам делается минимальное количество раз
https://github.com/Vadimfre/keksagram-Semashko/blob/963e04497931c0101806948c5e5adcec2203d098/kekstagram-clear/main.js#L72-L73
Здесь на каждой итерации цикла поиск будет проводиться заново. Правильно - вынести поиск шаблона за пределы цикла, а в цикле уже только клонировать

**Comment by Vadimfre** [comment]
Не увидел, исправил
https://github.com/Vadimfre/keksagram-Semashko/blob/1-task/kekstagram-clear/main.js?plain=1#L74-L76

**Comment by Vadimfre** [comment]
Не увидел, исправил https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plain=1#L74-L76

**Comment by Morfey216** [comment]
Вернемся к вопросу оптимизации поиска...
Область поиска нужно стараться максимально сокращать...
https://github.com/Vadimfre/keksagram-Semashko/blob/552c85e71a9c1ee7baebc59edd6a390fdcac0c60/main.js#L158-L160
В этом коде правильно будет вначале найти форму, а уже внутри нее искать оверлеи, кнопочки и т.д.

**Comment by Vadimfre** [comment]
То есть из родителя искать лучше, понял https://github.com/Vadimfre/keksagram-Semashko/blob/ab1d91f18403993c6e182cf626586d88c14708a2/main.js#L163-L165

**Comment by Morfey216** [comment]
Что понял - это хорошо! Но придется переделать 
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/51ca183c-e09f-4590-8b9d-6412fc3eed08)
Ты не внимательно прочел мою подсказку выше "В этом коде правильно будет вначале найти форму, а уже внутри нее искать оверлеи, кнопочки и т.д."
Задача - максимально сузить область поиска по DOM-дереву

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/e1a01606a81b44269522ed63a61f80b6ac5620cc/main.js#L163-L167 исправил вот так

**Comment by Morfey216** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/130786ec01926386a554b06399dee4feddbacfee/main.js#L167-L168
Кнопка закрытия находится не просто внутри формы загрузки, но и глубже внутри редактирования

**Comment by Vadimfre** [comment]
ну тут пришлось понадобилось порыться и добавить, не думаю, что это правильно  https://github.com/Vadimfre/keksagram-Semashko/blob/27592f68ff0968598d481729f51fa5e26f91a03c/main.js#L163-L170

**Comment by Morfey216** [comment]
Думаю, что  wrapper and container лишние
