### ISSUE TITLE
Нейминг переменных

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#6]
Перечитай заново все правила, по которым строятся имена различных сущностей
https://github.com/Vadimfre/keksagram-Semashko/blob/963e04497931c0101806948c5e5adcec2203d098/kekstagram-clear/main.js#L86

**Comment by Vadimfre** [comment]
подписал по привычке как в питоне, исправил  https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plane=1#L88

**Comment by Morfey216** [comment]
Исправить то исправил, да не везде... Я же рекомендовал перечитать ВСЕ правила ))
Вот тебе сразу пачка пациентов для исправления
https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js#L2-L8

**Comment by Vadimfre** [comment]
Прочитал, хотя и в прошлый раз читал, видимо чуть забыл вот все исправил https://github.com/Vadimfre/keksagram-Semashko/blob/982c592fc5e22bac56a773f8b2dc18a2eb4460b6/kekstagram-clear/main.js?plane=1#L2-L8

**Comment by Morfey216** [comment]
Гуд... Смущают две последние позиции... Сам скажи, гладя на название, 35 - это размер чего?

Поправил?

А теперь две первые...

**Comment by Vadimfre** [comment]
и опять нейменг... Скоро обязательно научусь, вот исправленный вариант всего 
https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L2-L8 думаю так будет лучше
