### ISSUE TITLE
Функциональность

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#7]
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/93d704e8-e9a8-4958-99cc-24b61b1de8e5)
Для таких сущностей лучше создавать отдельные функции, например getImg(), getParagraph()
Такой подход позволит структурировать код

**Comment by Vadimfre** [comment]
я понял, спасибо, вот как исправил все функции переназвал по нормальному(наверное)  https://github.com/Vadimfre/keksagram-Semashko/blob/f573a30ab0c9019c941ddadd7f9ab19c5858b90b/kekstagram-clear/main.js?plane=1#L101-L137 вызвал тоже по нормальному, а не в функции

**Comment by Vadimfre** [comment]
как я понимаю лучше скриншоты отправлять на такие большие куски кода?

**Comment by Morfey216** [comment]
> как я понимаю лучше скриншоты отправлять на такие большие куски кода?

Не обязательно )) 
Я тебе пересылаю скриншоты из редактора кода и делаю это по двум причинам:
1. Нужно как-то выделить отдельные участки кода, сделать на них акцент
2. Показать исправленный вариант

В обоих случаях это внутри ссылок из твоего репозитория сделать не получится

**Comment by Vadimfre** [comment]
окей, я понял, эту тему поправили всю?

**Comment by Morfey216** [comment]
> окей, я понял, эту тему поправили всю?

Неа )) К ней чуть позже вернемся, когда мелочи пофиксишь

**Comment by Morfey216** [comment]
Ну вот, пришло время вернуться к задаче с большой картинкой ...

1. Смотри - у тебя работа функции завязана статично на одном значении
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/1ebb4cd9-3933-4cc7-bbc3-64bdd6f06361)

Однако предполагается, что функция открытия большой картинки может открывать любую картинку из массива данных.
Чтобы решить эту задачу, правильнее будет передавать внутрь функции данные для того изображения, которое открываем.

2. Странная логика формирования данных внутри секции с картинкой
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/6d4a2f38-b47c-4603-8499-21ee04de3fbb)

То есть ты вначале открываешь окно, т.е. показываешь его пользователю, а только потом начинаешь наполнять его данными. Принято делать иначе: вначале готовим всё так как должно быть, а потом открываем.
И не понятно, почему наполнение комментариями вынесено вообще за пределы...

**Comment by Vadimfre** [comment]
https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L94-L103 ну вот сделал теперь вот так, получается сначала я добавил все в картинку, уже потом только удалил класс hidden.
 а по поводу 1, то теперь сделал вот так https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L105 оп и сюда передал аргумент ну а дальше уже в каждой функции работал с ним  https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L94-L102

**Comment by Morfey216** [comment]
Ну, почти...
Какие данные ты передаешь в функцию генерации комментариев? А какие должен?
https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L101

**Comment by Morfey216** [comment]
Далее...
Зачем в функцию передавать весь объект, если для работы нужна только его часть?
https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L126-L131
Передавать нужно только то, что реально требуется для работы внутри функции
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/9f3cce8c-3503-46fe-b23d-97d9175c2140)

**Comment by Vadimfre** [comment]
Ну как я понял сюда нужно сразу передавать https://github.com/Vadimfre/keksagram-Semashko/blob/de3c68c1d4430cbaceeb1b33446e0d26d238de7a/kekstagram-clear/main.js#L101 вот комментарии от фотографии, нет?
ну и тогда функция вот так меняется https://github.com/Vadimfre/keksagram-Semashko/blob/de3c68c1d4430cbaceeb1b33446e0d26d238de7a/kekstagram-clear/main.js#L126-L141

**Comment by Morfey216** [comment]
Здесь ошибка
https://github.com/Vadimfre/keksagram-Semashko/blob/de3c68c1d4430cbaceeb1b33446e0d26d238de7a/kekstagram-clear/main.js#L101
Ты зачем снова вытаскиваешь данные первой картинки? Ты ведь уже имеешь на руках photoData, то есть данные именно той картинки, которую собираешься открывать!
