### ISSUE TITLE
Добавление комментариев в DOM

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#8]
Тут сразу две большие проблемы...
1. Множественные операции нужно проводить на фрагменте
2. Операцию поиска по DOM-дереву нужно максимально сокращать

Проблема здесь
https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L136

**Comment by Vadimfre** [comment]
То есть добавлять в фрагмент лучше, ведь он не перерисовывает каждый раз страницу и получается нужно перерисовать страницу только 1 раз,? Кстати, прошу заметить, использовал константы))) https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L127-L128 https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L140-L143 получается когда добавлял в фрагмент то это было с цикле for, уже потом вне цикле добавляю его в dom

**Comment by Morfey216** [comment]
Да, эти моменты пофиксил, молодец.
Теперь идем дальше: для чего функция `createFullSizePictureComment `должна знать о каком-то внешнем окружении? А именно - о контейнере для комментариев `const commentsContainer = bigPicture.querySelector(".social__comments");`?

Правильным будет вернуть из функции фрагмент с набором комментариев, а уже в родительской функции вставить
https://github.com/Vadimfre/keksagram-Semashko/blob/de3c68c1d4430cbaceeb1b33446e0d26d238de7a/kekstagram-clear/main.js#L94-L103

Тогда ты сохранишь нормальную логику разделения функций по их зонам ответственности. А то получается что функция создания комментариев не только создает те самые комментарии, но еще и выполняет их добавление в DOM, забирая на себя не свою работу

**Comment by Morfey216** [comment]
Открою заново, так как обнаружился серьезный баг...
https://gyazo.com/96c7f61817364863a0d1d7a9beaf971e

А вот так происходит, если открыть одну и ту же фотку несколько раз подряд...
![image](https://github.com/Vadimfre/keksagram-Semashko/assets/42171361/c0f93c6c-f675-46f4-9e2f-558dd1010834)

Короче - контейнер надо чистить перед вставкой новых данных

**Comment by Vadimfre** [comment]
Ого, вот как я исправил https://github.com/Vadimfre/keksagram-Semashko/blob/2506c1ec71a12ae130592d54257123d2827bfc1c/main.js#L134-L138
