### ISSUE TITLE
Элемент vs Данные

### ISSUE THREAD

**Issue by Morfey216** [Vadimfre/keksagram-Semashko#9]
Давай мы договоримся, что в JS под элементом мы будем понимать именно элемент DOM-дерева
В этом фрагменте скорее всего речь идет о данных
https://github.com/Vadimfre/keksagram-Semashko/blob/7e2083139419d9e37f16c705f9640ce5a89cb04a/kekstagram-clear/main.js#L125
Соответственно эту особенность надо отразить в названии.
То же самое касается и во всех параметрах функций, перепроверь

**Comment by Vadimfre** [comment]
ого, интересно, ну вот я исправил https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L130 вот так решит что тут photoData, думаю нормально подходит этот нейминг

**Comment by Vadimfre** [comment]
ну и соответственно во всех функция тоже поменял, теперь там не (elem) https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L118 https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L135 https://github.com/Vadimfre/keksagram-Semashko/blob/03b780c599dbcc8c5c8c1ee4ab046ea576413934/kekstagram-clear/main.js#L107
